### ISSUE TITLE
Wishlist: Docker Compose file

### ISSUE THREAD

**Issue by floli** [jdreinhardt/docker-teedy#3]
Hello,

a `docker-compose.yaml` file for the pre-built Teedy images would be great to get started quickly!

**Comment by jdreinhardt** [comment]
Are you thinking a base compose with only Teedy, or more complex options including reverse proxies and external databases?

**Comment by floli** [comment]
I think for the time being a basic compose file to build on and get started was great!

**Comment by jdreinhardt** [comment]
Merged in.
